### ISSUE TITLE
Support up-to-date dependencies on the latest versions of packages

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/dart#28]
With up-to-date packages you can easily face issues that they depend on newer versions of other packages. 
List of all outdated dependencies could be found [here](https://pub.dev/packages/spine_client/score).

In my current case i face an issue with:
`spine_client` depends on `uuid ^2.0.2` which depends on `crypto ^2.0.0`
While to update `environment_config` to the latest one I require `crypto ^3.0.0`

This issue can be solved by updating `uuid` dependency to `3.0.4`.  

In general it worth it to update all dependencies to avoid such issues with other packages.

**Comment by dmdashenkov** [comment]
Resolved.
